baseURL = 'https://donkey.red/'
languageCode = 'en-us'
title = 'Red Donkey Technology Corp'
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap']

[params]
  brandName = 'Red Donkey'
  description = 'Red Donkey Technology Corp homepage'
  contactEmail = 'hi@donkey.red'
