baseURL = 'https://donkey.red/'
languageCode = 'en-us'
title = 'Red Donkey Technology Corp'
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap']

[params]
  description = 'Red Donkey Technology Corp'
  businessNumber = '753425818'
  contactEmail = 'hi@donkey.red'
